//
//  Export.swift
//  SpotifyRecommender
//
//  Created by 90303054 on 5/18/20.
//  Copyright © 2020 90303054. All rights reserved.
//

import Foundation

struct PlaylistInput: Codable {
    var name: String
    var description: String = "Playlist Generated by Spotify Recommender"
    var isPublic: Bool = true
    enum CodingKeys: String, CodingKey {
        case name
        case description
        case isPublic = "public"
    }
}

struct PlaylistOutput: Codable {
    var id: String
}

struct User: Codable {
    var id: String
}
